
site:
  about:
    siteName: Kudzu
    siteDescription: A monadic (I think...) recursive-descent parser written in Kotlin

theme:
  social:
    github: 'copper-leaf/kudzu'
  primaryColor: '#449999'
  bannerColor: '#449999'
  menu:
  - type: 'link'
    title: 'Home'
    url: '#{$0|baseUrl}/'
  - type: 'kotlindocClasses'
    title: 'Api Docs'
  trianglifyOptions:
    x_colors: ['#88ffe0', '#000000', '#88ffe0']
  useSidebarSearch: true

services:
  publications:
    stages:
      ghPages:
        branch: gh-pages
        latestDirName: latest
        publishType: CleanBranch
        username: copper-leaf
        repo: kudzu
